name: Build OrangeFox for Samsung A52s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses-dev lib32z1-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Install repo tool
      run: |
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo 'export PATH=$HOME/.bin:$PATH' >> ~/.bashrc
        export PATH=$HOME/.bin:$PATH

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Sync OrangeFox source
      run: |
        mkdir ~/orangefox
        cd ~/orangefox
        git clone https://gitlab.com/OrangeFox/sync.git sync
        cd sync
        ./orangefox_sync.sh --branch 12.1 --path ~/orangefox/fox_12.1

    - name: Clone device trees
      run: |
        cd ~/orangefox/fox_12.1
        git clone https://github.com/CRZX1337/orangefox_device_samsung_a52sxq.git device/samsung/a52sxq

    - name: Start build process
      run: |
        cd ~/orangefox/fox_12.1
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=a52sxq
        export LC_ALL="C"
        source build/envsetup.sh
        lunch twrp_a52sxq-eng && mka adbd recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-Recovery-a52sxq
        path: ~/orangefox/fox_12.1/out/target/product/a52sxq/OrangeFox*.img
