name: Build OrangeFox Recovery for a52sxq (Wiki Sync Method + Local SDK Script + PWD + LS DEBUG - FIX)

on:
  workflow_dispatch: # Ermöglicht manuelles Auslösen des Workflows über die GitHub-UI
  push:
    branches: [ main, master ] # Optional: Auslösen bei Push auf main oder master Branch
  pull_request: # Optional: Auslösen bei Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest # Nutzt Ubuntu als Build-Umgebung

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Prepare Build Environment (Wiki Step 0) # Wiki Schritt 0: apt install, clone scripts, env setup, sdk install
        run: |
          cd ~
          sudo apt install git aria2 -y

      - name: Clone OrangeFox Scripts (Wiki Step 3) # Wiki Schritt 3: git clone scripts repo
        run: |
          cd ~
          git clone https://gitlab.com/OrangeFox/misc/scripts

      - name: Run android_build_env.sh (Wiki Step 4 & 5) # Wiki Schritte 4 & 5: cd scripts & run script
        run: |
          cd ~/scripts
          sudo bash setup/android_build_env.sh

      - name: Run install_android_sdk.sh (Wiki Step 6) # Wiki Schritt 6: run install_android_sdk.sh - LOKALES SKRIPT! + PWD DEBUG
        run: |
          pwd # NEU: Aktuellen Arbeitsordner ausgeben!
          # cd ~/scripts  <-- ENTFERNT: Falscher cd-Befehl im Workflow-Kontext
          sudo bash scripts/install_android_sdk.sh # Verwende LOKALES Skript!

      - name: List SDK cmdline-tools Directory Content # NEU: Verzeichnisinhalt ausgeben - LS DEBUG - **VERSCHOBEN & WICHTIG!**
        run: |
          ls -l ~/android-sdk-linux/cmdline-tools # Inhalt von cmdline-tools auflisten
          ls -l ~/android-sdk-linux/cmdline-tools/bin # Inhalt von cmdline-tools/bin auflisten (falls vorhanden)

      - name: Install Dependencies (Redundant? - erstmal behalten) # Ergänzende Dependencies (könnte redundant sein, aber sicher ist sicher)
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses5-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.2-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python3 python3-pip repo

      - name: Install Repo (Redundant? - erstmal behalten) # Ergänze Repo Installation (könnte redundant sein, aber sicher ist sicher)
        run: |
          mkdir -p ~/.bin
          curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          export PATH=~/.bin:$PATH
          repo --version

      - name: Configure Git for GitLab Anonymous Access # Git Konfiguration für GitLab (kein Proxy)
        run: |
          git config --global --add http.noProxy gitlab.com
          git config --global --add https.noProxy gitlab.com

      - name: Set up Swap Space # Swap Space einrichten (bleibt erhalten)
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Cache Repo Sync # Caching für repo sync (bleibt erhalten)
        uses: actions/cache@v3
        id: cache-repo-sync
        with:
          path: orangefox
          key: repo-sync-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            repo-sync-${{ runner.os }}-

      - name: Sync OrangeFox Sources (Wiki Step 1 - orangefox_sync.sh) # Wiki Schritt 1: orangefox_sync.sh
        run: |
          mkdir ~/OrangeFox_sync # Wiki empfiehlt OrangeFox_sync Ordner
          cd ~/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git
          cd ~/OrangeFox_sync/sync/
          ./orangefox_sync.sh --branch 12.1 --path ~/orangefox # Sync nach ~/orangefox (unser Build-Verzeichnis)

      - name: Checkout Device Tree (Wiki Step 2) # Wiki Schritt 2: Device Tree
        run: |
          cd ~/orangefox # Wichtig: ins Sync-Verzeichnis wechseln!
          mkdir -p device/samsung/a52sxq
          git clone --depth=1 https://github.com/CRZX1337/orangefox_device_samsung_a52sxq.git device/samsung/a52sxq

      - name: Setup Build Environment (Wiki Step 3) # Wiki Schritt 3: Build Env Setup + Exports
        run: |
          cd ~/orangefox # Wichtig: ins Sync-Verzeichnis wechseln!
          export ALLOW_MISSING_DEPENDENCIES=true # Wiki Export
          export FOX_BUILD_DEVICE=a52sxq # Wiki Export - DEVICE NAME!
          export LC_ALL="C" # Wiki Export
          source build/envsetup.sh

      - name: Lunch Target (Wiki Step 3 - TWRP!) # Wiki Schritt 3: Lunch Target - TWRP!!!
        run: |
          cd ~/orangefox # Wichtig: ins Sync-Verzeichnis wechseln!
          lunch twrp_a52sxq-eng # WICHTIG: TWRP Lunch Target verwenden!!!

      - name: Make Recovery Image (Wiki Step 3) # Wiki Schritt 3: mka recoveryimage
        run: |
          cd ~/orangefox # Wichtig: ins Sync-Verzeichnis wechseln!
          mka recoveryimage

      - name: Upload Recovery Image Artifact # Artifact Upload (bleibt erhalten)
        uses: actions/upload-artifact@v4
        with:
          name: orangefox-recovery-a52sxq
          path: ~/orangefox/out/target/product/a52sxq/recovery.img # Pfad angepasst an Sync-Verzeichnis

      - name: Output Success Message # Success Message (bleibt erhalten)
        run: echo "OrangeFox Recovery Build erfolgreich abgeschlossen!"
