name: Build OrangeFox for Samsung A52s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximieren des Speicherplatzes
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Abhängigkeiten installieren
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses-dev lib32z1-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3

    - name: Repo-Tool installieren
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Quellcode auschecken
      uses: actions/checkout@v3

    - name: OrangeFox-Quellen synchronisieren
      run: |
        mkdir ~/OrangeFox_sync
        cd ~/OrangeFox_sync
        git clone https://gitlab.com/OrangeFox/sync.git sync
        cd sync
        ~/bin/repo init -u https://gitlab.com/OrangeFox/manifest.git -b fox_12.1
        ~/bin/repo sync --force-sync --no-tags --no-clone-bundle --optimized-fetch

    - name: Gerätedaten hinzufügen
      run: |
        cd ~/OrangeFox_sync/fox_12.1
        git clone https://github.com/CRZX1337/orangefox_device_samsung_a52sxq.git device/samsung/a52sxq

    - name: Build-Prozess starten
      run: |
        cd ~/OrangeFox_sync/fox_12.1
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=a52sxq
        export LC_ALL="C"
        source build/envsetup.sh
        lunch twrp_a52sxq-eng && mka adbd recoveryimage

    - name: Recovery-Image hochladen
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-Recovery-a52sxq
        path: ~/OrangeFox_sync/fox_12.1/out/target/product/a52sxq/OrangeFox*.img
