name: Build PBRP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python3 python-is-python3
    
    - name: Install repo
      run: |
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+rx ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH
    
    - name: Initialize repo and sync
      run: |
        mkdir pbrp_build
        cd pbrp_build
        repo init -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1
        repo sync
    
    - name: Clone device tree
      run: |
        cd pbrp_build
        git clone https://github.com/CRZX1337/android_device_samsung_a52sxq -b android-12.1 device/samsung/a52sxq
    
    - name: Build PBRP
      run: |
        cd pbrp_build
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch omni_a52sxq-eng
        mka recoveryimage
    
    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: recovery.img
        path: pbrp_build/out/target/product/a52sxq/recovery.img
